version: '3.2'

services:
  droplet:
    build: ./
    ports:
      - "8080:8080"
    links:
      - mongo
    networks:
      - droplet_net
  mongo:
    image: mongo:3-stretch
    ports:
      - "27017:27017"
    networks:
      - droplet_net

networks:
  droplet_net:
